name: Build

on:
    push:
        branches:
            - '*'

env:
    PLUGIN_NAME: NoClippyX    

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.*
            - name: Install Dependencies
              run: dotnet restore
            - name: Download Dalamud
              run: |
                Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
                Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
            - name: Build
              run: |
                dotnet build --no-restore --configuration Release --nologo
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: build.zip
                path: |
                    $PLUGIN_NAME/bin/x64/Release/$PLUGIN_NAME/latest.zip
                    $PLUGIN_NAME/bin/x64/Release/$PLUGIN_NAME/$PLUGIN_NAME.json
